### ISSUE TITLE
#US03 Como usuario quiero acceder desde cualquier dispositivo para mayor comodidad

### ISSUE THREAD

**Issue by eduscba** [aguirre-valeria/full-stack-project#27]
Diseño responsivo

**Comment by aguirre-valeria** [comment]
### Diseño responsive.
- Vista escritorio PC: 
![vista-escritorio](https://user-images.githubusercontent.com/102261096/196320412-214c7e45-6f40-4ed9-99c9-27b76befe400.jpg)

- Vista celular:
![vista-celular](https://user-images.githubusercontent.com/102261096/196320436-b68b09cc-9869-44ba-831d-8e4b436d207b.jpg)
